#######################################################################################
# Book settings
title : sparse-ir
author: Many authors
copyright: "2022"

# Information about where the book exists on the web
description: >-
  Online document for sparse-ir

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : cache

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : false

# #######################################################################################
# Interact link settings
notebook_interface            : "jupyterlab"

#######################################################################################
# Launch button settings
repository:
  url                         : https://github.com/SpM-lab/sparse-ir-doc.git
  path_to_book                : ""

latex:
  latex_engine                : "pdflatex"
  latex_documents:
    targetname: book.tex

sphinx:
  config:
    language: en